version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - bckp-php8.2:/var/www/html/bckp
        ports:
            - "9900:80"
        networks:
            - app-network
        restart: always

networks:
    app-network:
        driver: bridge

volumes:
    bckp-php8.2:
